services:
  - type: web
    name: emotion-vortex
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    pythonVersion: "3.12"   # ‚Üê THIS LINE
